# Workflow for CI on Node.js
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # For self-hosted runner
    strategy:
      matrix:
        node-version: [18.x]
        # Add additional Node.js versions here if needed, e.g., [18.x, 20.x, 22.x]

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Build the project (optional if no build step is required)
      - name: Build Project
        run: npm run build --if-present

      # Step 5: Run tests
      - name: Run Tests
        run: npm test
